- hosts: sandbox
  sudo: yes
  gather_facts: false
  vars_files:
    - vars/sandbox/main.yml
  pre_tasks:
    - shell: "[ -f /tmp/deploy.lock ] && echo 1 || echo 0"
      register: provision_in_progress

    - shell: cat /tmp/deploy.lock
      register: who_is_deploying
      when: provision_in_progress.stdout == "1"

    - fail: msg="The system may not be provisioned because {{who_is_deploying.stdout}} is deploying it right now"
      when: provision_in_progress.stdout == "1" and force_update is not defined

    - shell: echo `whoami` from `hostname`
      register: register_deployer
      sudo: no
      delegate_to: 127.0.0.1

    - shell: touch /tmp/deploy.lock && echo {{register_deployer.stdout}} > /tmp/deploy.lock

  post_tasks:
    - shell: rm /tmp/deploy.lock
  roles:

    - prepare-deploy-pack-for-frontend
    - deploy-frontend

    - prepare-deploy-pack-for-backend
    - deploy-backend

    - run-npm-install
    - run-migrate
    - init-or-restart-node-service
#    - update_crontab
